development:
  adapter: postgresql
  encoding: unicode
  database: finder_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: finder_test
  pool: 5
  username:
  password:
