# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80049ff29b30bb560c8a4c5fdfbbd63a37b701473340dd678f1eaac40aff9f3470fa1e81f59f5aa91ef68e12ec8297ac0d0cb23e57c03ca94986e7555f76cce3

test:
  secret_key_base: bbc97009641e9300020deea1a734d3d032dceceb50a87e1455ede374b3a9dca7b8139ef4d0680d3f1fa83296bb4c0d9b2b89b0ea07a413409d42760b424cd3f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
